[workspace]
members = ["src-ui", "src-tauri", "share", "backend"]
exclude = []

[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["Dvorak Chen"]
repository = "https://github.com/dvorakchen/dvorak-epic-games-launcher"
description = "A better Epic Games Launcher"
license = "MIT"


[workspace.dependencies]
email_address = "0.2.4"
rand = "0.8.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.35", features = ["serde"] }
share = { path = "./share" }
gloo = { version = "0.11.0", features = ["timers", "futures", "storage"] }
