name: dvorak-epic-games-launcher-api
services:
  server:
    build:
      context: .
      target: final
    networks:
      - apinet
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=./epic.db
      - RUST_LOG=debug

networks:
  apinet:
    name: epicaipnetwork
    # external: true
