[package]
name = "share"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
dependencies.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }